name: Prod release
on:
  # Action is triggered on every commit to the prod branch.
  push:
    branches:
    - prod

jobs:
  release:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3
      with:
        path: prod

    # Now checkout the release branch to release folder.
    - uses: actions/checkout@v3
      with:
        ref: release
        path: release

    # Would like a version of manifest.json that is usable from browsers
    # for grist-static. CORS wildcard is not set on releases, but is set
    # on github pages. Also jsdelivr can mirror branches, but not releases.
    - name: Make a release branch that includes manifest.json
      run: |
          cd prod
          git config user.name "Paul's Grist Bot"
          git config user.email "<paul+bot@getgrist.com>"
          ./buildtools/publish.js
          git add -f manifest.json
          git commit -m "adding manifest"
          # Now prepare the release branch.
          cd ../release
          git config user.name "Paul's Grist Bot"
          git config user.email "<paul+bot@getgrist.com>"
          # remove everything except .git .gitignore and master
          find . -maxdepth 1 -mindepth 1 -not -name .git -not -name .gitignore -not -name master -exec rm -rf {} \;
          # Now copy the material from prod to release
          cd ../prod
          git archive --format=tar HEAD | (cd ../release && tar xf -)
          git add -A
          git add -f manifest.json
          git commit -m "prd preview"
          git push --set-upstream origin HEAD:release -f
